Update stdout colors

diff --git a/gh-search b/gh-search
--- a/gh-search
+++ b/gh-search
@@ -4,23 +4,29 @@
 TODAY=$(date +%F)
 CACHEDIR=$HOME/.cache/gh-search
 
+RED='\e[38;5;31m'
+GREEN='\e[38;5;32m'
+YELLOW='\e[38;5;33m'
+BLUE='\e[38;5;39m'
+MAGENTA='\e[38;5;35m'
+CYAN='\e[38;5;36m'
+GREY='\e[37m'
+NORMAL='\e[0m'
+
 DEFAULT_OUTDIR=/tmp/gh-search/$TODAY
 DEFAULT_PAGE_LIMIT=1
 DEFAULT_PAGE_START=1
-DEFAULT_PER_PAGE=100
+DEFAULT_PER_PAGE=25
 DEFAULT_QUERY='NOT+is:fork'
 
-GHSEARCH_OUTDIR=${GHSEARCH_OUTDIR:-$DEFAULT_OUTDIR}
-GHSEARCH_PAGE_LIMIT=${GHSEARCH_PAGE_LIMIT:-$DEFAULT_PAGE_LIMIT}
-GHSEARCH_PAGE_START=${GHSEARCH_PAGE_START:-$DEFAULT_PAGE_START}
-GHSEARCH_PER_PAGE=${GHSEARCH_PER_PAGE:-$DEFAULT_PER_PAGE}
-GHSEARCH_QUERY=${GHSEARCH_QUERY:-$DEFAULT_QUERY}
-GHSEARCH_CONTENT=$GHSEARCH_CONTENT
-GHSEARCH_VERBOSE=$GHSEARCH_VERBOSE
-GHSEARCH_TEST_RUN=$GHSEARCH_TEST_RUN
-
-_flag=
-_header=
+export GHSEARCH_OUTDIR=${GHSEARCH_OUTDIR:-$DEFAULT_OUTDIR}
+export GHSEARCH_PAGE_LIMIT=${GHSEARCH_PAGE_LIMIT:-$DEFAULT_PAGE_LIMIT}
+export GHSEARCH_PAGE_START=${GHSEARCH_PAGE_START:-$DEFAULT_PAGE_START}
+export GHSEARCH_PER_PAGE=${GHSEARCH_PER_PAGE:-$DEFAULT_PER_PAGE}
+export GHSEARCH_QUERY=${GHSEARCH_QUERY:-$DEFAULT_QUERY}
+export GHSEARCH_CONTENT=$GHSEARCH_CONTENT
+export GHSEARCH_VERBOSE=$GHSEARCH_VERBOSE
+export GHSEARCH_TEST_RUN=$GHSEARCH_TEST_RUN
 
 mkdir -p $CACHEDIR
 
@@ -34,20 +40,37 @@ then (.items | map([
 else ""
 end'
 
-_downloading() {
-    echo -e "\e[38;5;39m=>\e[38;5;81m Downloading \e[38;5;39m$1\e[0m" 3>&2 2>&1 >&3 3>&-
-    [[ $GHSEARCH_VERBOSE -eq 1 ]] && echo -e "   $2" 3>&2 2>&1 >&3 3>&-
-}
+_usage() {
+    echo -e "
+    ${CYAN}gh-search${NORMAL} - search github code
 
-_saveTo() { echo -e "\e[38;5;11m=>\e[38;5;3m Saved to \e[38;5;11m$*\e[0m" 3>&2 2>&1 >&3 3>&-; }
+    export GITHUB_TOKEN=..
 
-_errorMsg() {
-    echo -e "\e[38;5;9m[ERROR]\e[0m $@" 3>&2 2>&1 >&3 3>&-
+    gh-search \\
+      --search ${GREY}[SEARCH_TERM]${NORMAL} \\
+      --language ${GREY}[LANGUAGE]${NORMAL} \\
+      --user ${GREY}[USER]${NORMAL} \\
+      --org ${GREY}[ORG]${NORMAL} \\
+      --repo ${GREY}[REPO]${NORMAL} \\
+      --extension ${GREY}[EXT]${NORMAL} \\
+      --per-page ${GREY}[NUM]${NORMAL} \\
+      --path ${GREY}[PATH]${NORMAL} \\
+      --out ${GREY}[DIR]${NORMAL}
+  "
     exit 1
 }
 
 _chksum() {
     echo "$@" | md5sum | awk '{print $1}'
+}
+
+_save() {
+    echo -e "Save ${BLUE}$1${NORMAL}\n    to ${GREY}$2${NORMAL}\n"
+}
+
+_errorMsg() {
+    echo -e "\e[38;5;9m[ERROR]\e[0m $@" 3>&2 2>&1 >&3 3>&-
+    exit 1
 }
 
 _curl() {
@@ -57,7 +80,6 @@ _curl() {
     curl_args=(-s --create-dirs -o "$CACHEFILE" "$@")
 
     if [[ ! -f "$CACHEFILE" ]]; then
-        _downloading "${curl_args[-1]}" "$CACHEFILE"
         curl "${curl_args[@]}"
     fi
     cat $CACHEFILE
@@ -76,7 +98,7 @@ _store() {
         _curl "${GITHUB_URL}" >"$OUTPUTPATH"
     fi
     if [[ -f "$OUTPUTPATH" && -s "$OUTPUTPATH" ]]; then
-        _saveTo "$OUTPUTPATH"
+        _save "${GITHUB_URL}" "$OUTPUTPATH"
         return 0
     fi
     return 1
@@ -99,9 +121,9 @@ _fetch() {
     if [[ ${#_items[@]} -eq $GHSEARCH_PER_PAGE ]]; then return 0; else return 1; fi
 }
 
-main() {
+codesearch() {
     [[ -z $GITHUB_TOKEN ]] &&
-        _errorMsg 'GITHUB_TOKEN is not set in the environment. Run `export GITHUB_TOKEN`'
+        _errorMsg 'GITHUB_TOKEN is not set in the'
 
     [[ -z $GHSEARCH_CONTENT ]] && ! grep -q filename: <<<"$API_URL" &&
         _errorMsg "Missing search term. Rerun with '--search <TERM>' or '--filename .bashrc'"
@@ -116,28 +138,38 @@ main() {
     done
 }
 
+#------------------------------------------------------------------------------#
+#-- RUN
+#------------------------------------------------------------------------------#
 ARGS=($@)
 queryargs=()
 
 for i in "${!ARGS[@]}"; do
+
     index="${ARGS[$i]}"
     next="${ARGS[$i + 1]}"
 
+    if [[ "$next" == *\ * ]]; then
+        qnext="\"${next// /%20}\""
+        quoted_next="\"${next// /%20}\""
+    fi
+
     case "${index}" in
+    -h | --help) _usage ;;
     -l | --limit) GHSEARCH_PAGE_LIMIT="$next" ;;
     -o | --out) GHSEARCH_OUTDIR="$next" ;;
     -p | --page) GHSEARCH_PAGE_START=$next ;;
     -t | --token) GITHUB_TOKEN="$next" ;;
     -q | --query) GHSEARCH_QUERY="$next" ;;
     -N | --no-defaults) GHSEARCH_QUERY= ;;
-    -s | --search) GHSEARCH_CONTENT="${next// /%20}" ;;
+    -s | --search) GHSEARCH_CONTENT="${next// /+}" ;;
     -V | --verbose) GHSEARCH_VERBOSE=1 ;;
     -P | --per[_-]page) GHSEARCH_PER_PAGE=$next ;;
-    _T | --test-run) GHSEARCH_TEST_RUN=1 ;;
+    -T | --test-run) GHSEARCH_TEST_RUN=1 ;;
 
     # QUERY PARAMETER
     --language) queryargs+=("language:$next") ;;
-    --extension) queryargs+=("extension:$next") ;;
+    --ext*) queryargs+=("extension:$qnext") ;;
     --filename) queryargs+=("filename:$next") ;;
     --repo) queryargs+=("repo:$next") ;;
     --symbol) queryargs+=("symbol:$next") ;;
@@ -166,8 +198,4 @@ echo -e "
 q=\e[38;5;2m${GHSEARCH_CONTENT%+}\e[0m+\e[38;5;3m${GHSEARCH_QUERY%+}\e[0m+\e[38;5;4m${QUERY_ARGS%+}\e[0m
 "
 
-if [[ $GHSEARCH_TEST_RUN -eq 1 ]]; then
-    env | sort
-else
-    main
-fi
+codesearch
